version: 0.0
os: linux
files:
  - source: app
    destination: /var/www
  - source: DeploymentScripts/webapi.service
    destination: /etc/systemd/system
hooks:
  BeforeInstall:
    - location: DeploymentScripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: DeploymentScripts/stop_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: DeploymentScripts/start_app.sh
      timeout: 300
      runas: root